### ISSUE TITLE
add tag_id && tag_type to base class for objects

### ISSUE THREAD

**Issue by light5551** [OSLL/dt-gui-tools_old#12]

**Comment by HadronCollider** [comment]
`SignObject` не имеют указанных полей, несмотря на обязательное их наличие (поскольку они являются тегами) + комментарии https://github.com/OSLL/dt-gui-tools/pull/17/files - блокирует #29

**Comment by light5551** [comment]
https://github.com/OSLL/dt-gui-tools/pull/35
